#this is just listing the current location of the folder
#for each run of each code. It does NOT do any translating 
#between filenames and timesteps (see ytload and lookup_snap_path
#in agora_snapshot.py). 
locations = {'art_C1':'Cal_step1.1/ART_I',
             'changa_C1':'Cal_step1.1/ChaNGa',
             'enzo_C1':'Cal_step1.1/ENZO',
             'gadget_C1':'Cal_step1.1/GADGET-3/v1',
             'gear_C1':'Cal_step1.1/GEAR',
             'gizmo_C1':'Cal_step1.1/GIZMO',
             'ramses_C1':'Cal_step1.1/RAMSES',
             'art_C2':None,
             'changa_C2':None,
             'enzo_C2':None,
             'gadget_C2':None,
             'gear_C2':None,
             'gizmo_C2':None,
             'ramses_C2':None,
             'art_C3':None,
             'changa_C3':None,
             'enzo_C3':None,
             'gadget_C3':None,
             'gear_C3':None,
             'gizmo_C3':None,
             'ramses_C3':None,
             'art_C4':None,
             'changa_C4':None,
             'enzo_C4':None,
             'gadget_C4':None,
             'gear_C4':None,
             'gizmo_C4':None,
             'ramses_C4':None,
             'art_CR':'ThinTimeSteps/ART-I/Cosmo_v14_13lev_Thin/',
             'changa_CR':'ThinTimeSteps/CHANGA/Cal4_Johnny',
             'enzo_CR':None,
             'gadget_CR':'ThinTimeSteps/GADGET-3/Cal4',
             'gear_CR':'ThinTimeSteps/GEAR/Cal4',
             'gizmo_CR':'ThinTimeSteps/GIZMO',
             'ramses_CR':'ThinTimeSteps/RAMSES/Cal4',
            }
